### ISSUE TITLE
Colaboradores

### ISSUE THREAD

**Issue by flavioduart** [flavioduart/informatica29VelhandoeCeiando#1]
Quando os membros forem adicionados como colaboradores, comentar aqui e o último fechar a issue.

**Comment by caahreginaa** [comment]
Olá, fui adicionada. :dancer:

**Comment by drbeco** [comment]
Todo issue deve ter label e milestone. Lembre sempre, pois não vou ficar constantemente escrevendo sobre isso.

**Comment by flavioduart** [comment]
Desculpe professor.

**Comment by eilins** [comment]
Boa noite, fui adicionado.
