### ISSUE TITLE
Melhoria da função computadorxcomputador

### ISSUE THREAD

**Issue by flavioduart** [flavioduart/informatica29VelhandoeCeiando#11]
Gente, do jeito que ta essa função, ele não avisa quem ganhou, ou quando deu empate, precisa ser feito uma função pra verificar isso.

**Comment by caahreginaa** [comment]
Sim, a função a parte poderá ser usada por todos os modos de jogo, não só a computadorxcomputador

**Comment by caahreginaa** [comment]
Função analise criada e funcional.
