### ISSUE TITLE
Melhoria na funcao analise

### ISSUE THREAD

**Issue by caahreginaa** [flavioduart/informatica29VelhandoeCeiando#12]
Estava observando o código e acredito que seria melhor que a funcao analise retornasse valores diferentes dependendo do jogador que ganhou a partida.

**Comment by flavioduart** [comment]
Verdade Cássia, não tinha pensando nisso, fica melhor ate pro programa, eu creio.

**Comment by eilins** [comment]
Realmente. Ficaria melhor mesmo, ao invés de cada "if" fazer um printf pra mostrar quem ganhou, fazendo isso, só é avisar o valor retornado, e fazer dois printfs.

**Comment by caahreginaa** [comment]
Já fiz a melhoria e adicionei printfs informando quem ganhou.
