### ISSUE TITLE
Tabela exemplo

### ISSUE THREAD

**Issue by flavioduart** [flavioduart/informatica29VelhandoeCeiando#13]
Seria bom ter uma tabela padrão, com as casas enumeradas de 0 a 8, pra o usuário saber onde se localiza cada casa, pra ajudar na hora de jogar.

**Comment by caahreginaa** [comment]
Eu concordo que seria bom adicionar essa tabela.

**Comment by caahreginaa** [comment]
Vinicius começou e eu terminei de editar essa tabela, já é possível utilizá-la em outras funções do código, basta enviar como argumento para a função imprimetabu(int x) qualquer inteiro diferente de 1.
