### ISSUE TITLE
Função de jogada aleatória

### ISSUE THREAD

**Issue by eilins** [flavioduart/informatica29VelhandoeCeiando#14]
Acho que se a gente fizer uma função que faça jogadas aleatórias, deixará o nosso código melhor, menor, e mais fácil de ser entendido. Toda vez que quisermos botar algo aleatório, só seria chamar a função.

**Comment by flavioduart** [comment]
Eu concordo, Vinícius. E vai ser fácil implementar.

**Comment by caahreginaa** [comment]
Concordo, vai facilitar muito as coisas e simplificar o código.

**Comment by flavioduart** [comment]
Pronto, a função está feita! :dancers:
