### ISSUE TITLE
Nível fácil

### ISSUE THREAD

**Issue by caahreginaa** [flavioduart/informatica29VelhandoeCeiando#15]
Pessoal, como já temos uma função para jogadas aleatórias e uma função para que o usuário jogue, podemos começar a fazer o nível fácil da função jogador x computador.

**Comment by flavioduart** [comment]
Verdade, e depois damos início aos outros níveis.

**Comment by eilins** [comment]
Ok, vamos lá, para vê se conseguimos atingir a meta de fazer até o nível médio por hoje.

**Comment by caahreginaa** [comment]
Nível fácil criado e funcionando.
