### ISSUE TITLE
Uso dos IFs

### ISSUE THREAD

**Issue by eilins** [flavioduart/informatica29VelhandoeCeiando#16]
Galera, na função humanoxcomputador estou tentando achar uma maneira de não utilizar tantos ifs para as varias condições que irão existir, para não deixar o código muito extenso, ou até mesmo coloca-los dentro de um único laço. O que vocês sugerem?

**Comment by caahreginaa** [comment]
Acho que devemos pensar numa forma de colocar esses ifs num for ou usar um while.

**Comment by flavioduart** [comment]
Pra diminuir os ifs, acho que a melhor maneira é fazendo um laço mesmo

**Comment by caahreginaa** [comment]
Fiz uma otimizaçao dos ifs utilizando um for e outros artificios.
