### ISSUE TITLE
erro na chamada da função

### ISSUE THREAD

**Issue by eilins** [flavioduart/informatica29VelhandoeCeiando#17]
Como posso resolver quando uma função minha da erro por dizer que ela contem pouco argumento?

**Comment by caahreginaa** [comment]
Se isso aconteceu, você provavelmente não esta enviando a quantidade correta de argumentos, exemplo:
```
Protótipo:
void funcao(int a, int b);
Chamada:
funcao(x);
```
Falta um argumento ser passado para a função.

**Comment by flavioduart** [comment]
Exatamente isso que Cássia falou, aconteceu comigo quando fiz uma das funções desse programa, mas consegui ajeitar.

**Comment by eilins** [comment]
Ah, entendi agora. Valeu, problema corrigido.
