### ISSUE TITLE
Computador começa com O no nivel fácil.

### ISSUE THREAD

**Issue by caahreginaa** [flavioduart/informatica29VelhandoeCeiando#18]
Pessoal, foi dito por e-mail pelo professor Ruben que quem começasse o jogo, começaria sempre com X, mas na funcao de computador x humano, nivel facil, quando o  computador começa, ele começa com O.

**Comment by flavioduart** [comment]
Se a gente colocar uma pergunta pra quem vai começar, e assim, o escolhido começaria com X e o segundo com O, não resolveria o problema?

**Comment by caahreginaa** [comment]
Já tem uma pergunta pra quem vai começar, quando é escolhido o computador, o computador começa, e vice-versa, o problema é que quem começar deve sempre começar com X, mas não é assim que esta a estrutura lógica do programa.

**Comment by eilins** [comment]
Acabei de corrigir o problema.
