### ISSUE TITLE
Problema na mensagem de erro

### ISSUE THREAD

**Issue by eilins** [flavioduart/informatica29VelhandoeCeiando#19]
Quando apertamos uma casa já selecionada antes, o programa ao invés de dar a mensagem de default, ele dá só que a mensagem fica num loop infinito. O que poderia ter ocasionado?

**Comment by caahreginaa** [comment]
Acredito que isso está acontecendo porque a pergubta e o scanf que guardam a resposta estão fora do do while, então o programa entra num loop infinito pois a variável nunca muda e sempre aparecerá jogada inválida.

**Comment by flavioduart** [comment]
Exatamente como Cássia falou, eu testei ela dentro do laço, como ela sugeriu, e pegou. Agora o bug está resolvido.
