### ISSUE TITLE
Quadrado mágico

### ISSUE THREAD

**Issue by drbeco** [flavioduart/informatica29VelhandoeCeiando#21]
Vocês sabem o que é na matemática um **quadrado mágico**?

E qual a relação que tem com o jogo-da-velha?

![image](https://cloud.githubusercontent.com/assets/5805111/11985064/d6dd5430-a99f-11e5-95be-b929a642fd23.png)

**Comment by flavioduart** [comment]
Professor, de acordo com a pesquisa que realizei, um quadrado vai ser matematicamente "mágico" quando a soma dos números de cada linha, coluna e diagonais for igual, ou seja, dando o mesmo resultado. No jogo da velha é isso que acontece; quando um jogador faz em sequencia uma linha, coluna ou diagonal, ele é eleito o vencedor, ou seja, usa a mesma ideia do quadrado mágico. Isso vai nos ajudar bastante no nosso código, obrigado!!

**Comment by caahreginaa** [comment]
Pesquisei e encontrei o mesmo que Flávio. Aplicando esse conceito para nosso programa, poderíamos atribuir um número a cada casa de modo a formar um quadrado mágico e quando a soma dos números numa linha, coluna ou diagonal desse determinado número, um jogador terá ganho o jogo.

**Comment by eilins** [comment]
Que massa, algo tão simples, mas com uma explicação logica matemática por trás. Não sabia, mas diante disso, vamos fazer o possível para aprender e implementar.
