### ISSUE TITLE
Combinação C9,3

### ISSUE THREAD

**Issue by drbeco** [flavioduart/informatica29VelhandoeCeiando#22]
A combinação C9,3 indica de quantas maneiras diferentes se pode pegar 3 itens de um grupo de nove. 

Por exemplo, um grupo com as 9 primeiras letras do alfabeto: `{a, b, c, d, e, f, g, h, i}`. As combinações seriam:

```
abc
abd
abe
abf
abg
abh
abi
acd
...
aci
ade
...
adi
...
bcd
...
bci
...
ghi
```

Na combinação a ordem não importa. Portanto escolher `abc` é o mesmo que escolher `bca`, por exemplo.

Para calcular a combinação `C9,3` usa-se o binomial `(9 3) = 9! / (3! * (9-3)!) = 84` possibilidades.

Se ao invés de letras do alfabeto, tivermos números de `{0, 1, 2, 3, 4, 5, 6, 7, 8}` o raciocínio é o mesmo. As soluções seriam `S={012, 013, ... 018, 023, ..., 678}`

Faça uma função que imprima todas as 84 soluções de combinações possíveis.

Pergunta: como essa função poderá ser usada no jogo-da-velha em conjunto com o quadrado mágico?

**Comment by caahreginaa** [comment]
Acredito que unindo essas combinações com a ideia de quadrado mágico, é possível acharmos todas as combinações com as quais é possível ganhar o jogo.

**Comment by eilins** [comment]
Vai ser um pouco complicado, alias esta sendo, aplicar essa ideia, mas é algo que deixará o jogo com um diferencial e um raciocínio mais inteligente. Vamos continuar tentando, galera.

**Comment by flavioduart** [comment]
Os resultado da combinação poderiam ser combinados com um quadrado mágico desse tipo, para achar as possibilidades de ganhar o jogo. ![image](https://cloud.githubusercontent.com/assets/13753641/12008237/8d562a20-ac0c-11e5-8912-f64e96d089b8.jpeg)

**Comment by caahreginaa** [comment]
A função foi criada :nail_care:

**Comment by flavioduart** [comment]
Função criada, professor.
