### ISSUE TITLE
Feliz Natal!

### ISSUE THREAD

**Issue by drbeco** [flavioduart/informatica29VelhandoeCeiando#23]
**Feliz Natal!**

Um excelente dia de Natal para todos!

**Comment by caahreginaa** [comment]
Feliz Natal, professor! :christmas_tree: :santa:

**Comment by flavioduart** [comment]
Feliz Natal, professor, e a todos colaboradores!! :smile_cat: :santa:

**Comment by eilins** [comment]
Feliz Natal a todos!! :santa: :snowman:
