### ISSUE TITLE
Nome do jogador na funcao nivelfacil computador x humano

### ISSUE THREAD

**Issue by caahreginaa** [flavioduart/informatica29VelhandoeCeiando#24]
Pessoal, nesta função o nome do jogador não esta aparecendo, quando o programa roda, ficam uns caracteres estranhos ao invés do nome.

**Comment by flavioduart** [comment]
Cassia, eu creio que seja algum problema na declaração do char, pra dar esse bug.

**Comment by eilins** [comment]
Ou talvez na impressão também. Pode ser que alguém tenha digitado errado o char a ser impresso no printf

**Comment by flavioduart** [comment]
Eu ajeitei a declaração do char na função, e agora o nome do jogador aparece. :ghost:
