### ISSUE TITLE
Jogo continuou apos computador ter vencido

### ISSUE THREAD

**Issue by caahreginaa** [flavioduart/informatica29VelhandoeCeiando#25]
Pessoal, rodei o programa agora testando e na funçao nivel facil humanoxcomputador, o computador havia ganhado, mas mesmo assim a funçao continuou.

**Comment by eilins** [comment]
Provavelmente este é um problema na funcao analise. Vou testar e ver se com os outros tipos de jogo isso também esta ocorrendo.

**Comment by eilins** [comment]
Como eu falei, o problema era na funçao analise. Percebi também que o bug só ocorria com o jogador que usava O, pois mudamos o numero que representava a O nas outras funçoes, mas não na análise. Já alterei, bug corrigido.
