### ISSUE TITLE
Tamanho do nome do jogador na funcao nivelfacil computador x humano

### ISSUE THREAD

**Issue by flavioduart** [flavioduart/informatica29VelhandoeCeiando#26]
Pessoal, Cássia relatou um bug que o nome do jogador não estava aparecendo na função citada acima, então eu corrigi. Agora o nome aparece, mas tem um limite de caracteres, passou de 6, ele bota caracteres estranhos. Quero a ajuda de vocês.

**Comment by caahreginaa** [comment]
Consegui corrigir o bug apenas alterando algumas variáveis.
