### ISSUE TITLE
tab sem ser variável global

### ISSUE THREAD

**Issue by eilins** [flavioduart/informatica29VelhandoeCeiando#27]
Galera,diante da mudança, onde teremos que declarar  tab[3][3] na int main, qual seria a solução mais pratica para passar a matriz como argumento de uma função?

**Comment by caahreginaa** [comment]
tab[3][3] é declarado como int na main, é adicionado nos protótipos da função que elas receberão uma variável no formato int tab[3][3] e depois enviamos tab na chamada da função.
