### ISSUE TITLE
como eliminar as repetições

### ISSUE THREAD

**Issue by eilins** [flavioduart/informatica29VelhandoeCeiando#28]
Galera, como podemos gerar todas as combinações possíveis eliminando as repetições quando implementar a função no jogo?

**Comment by caahreginaa** [comment]
Acredito que podemos ordenar a combinação em ordem crescente e depois comparar uma a uma. Caso sejam iguais, uma delas é apagada da memória.

**Comment by caahreginaa** [comment]
Adicionei na funçao combinacao o que eu citei acima e a função imprime apenas as 84 combinações.
