### ISSUE TITLE
Funcao jogadanivelmedio

### ISSUE THREAD

**Issue by caahreginaa** [flavioduart/informatica29VelhandoeCeiando#29]
Pessoal, acredito que nessa função podemos editar os ifs para que o computador jogue impedindo o jogador de ganhar. Da forma como esta agora, dependendo da posição do if, isso pode não acontecer.

**Comment by eilins** [comment]
Podemos editar a função modificando o diferente de 0 para uma variável qualquer quando for a jogada de outro jogador, para que o oponente possa marcar na tabela a sua jogada.

**Comment by eilins** [comment]
Galera, problema corrigido!
