### ISSUE TITLE
Milestones com data errada

### ISSUE THREAD

**Issue by drbeco** [flavioduart/informatica29VelhandoeCeiando#3]
Como está:

![image](https://cloud.githubusercontent.com/assets/5805111/11943311/8f328608-a81b-11e5-8aa0-d904120affef.png)

Como deveria estar:

```
Releases (milestones):
v0.1 - 22/Dez/15 - esqueleto e todos arquivos, AUTHORS definido, todos colaboradores adicionados (eu inclusive)
v0.2 - 26/Dez/15 - versão funcionando o nível 1 - fácil
v1.0 - 28/Dez/15 - versão final
```

**Comment by caahreginaa** [comment]
Eu que editei as milestones e coloquei as datas corretas, MAS por algum motivo o github sempre atrasa em um dia a data das milestones que edito.
![milestones](https://cloud.githubusercontent.com/assets/13753523/11943541/c981fa00-a825-11e5-9b38-cf3902dc3311.jpg)

**Comment by caahreginaa** [comment]
Deixarei para que os outros editem milestones então, é o jeito (?).

**Comment by drbeco** [comment]
Deixe para outro editar. Da sua parte, confira fuso horário tanto do computador que usa quanto do site github.

**Comment by flavioduart** [comment]
Pronto, resolvido. Data das milestones alteradas.
