### ISSUE TITLE
inicialização do nível dificil

### ISSUE THREAD

**Issue by eilins** [flavioduart/informatica29VelhandoeCeiando#30]
Galera, negocio agora é o seguinte,vamos começar a montar o nível difícil, a ideia é: Colocar uma variável na função nivelmedio e tipo, se ela retornar 0, ela chama a função de jogada aleatória, caso retorne 1, não. Basicamente vamos mudar a chamada de jogada aleatória que está presente na função jogada nível médio para a função nível médio. Vocês entenderam?

**Comment by caahreginaa** [comment]
Acho uma boa ideia, para podermos usar a função jogadanivelmedio no nivel dificil.

**Comment by flavioduart** [comment]
Vai ajudar bastante da função do nível difícil, é uma boa.

**Comment by eilins** [comment]
Galera, implementei a ideia, e pelo visto tudo certo. Valeu.
