### ISSUE TITLE
nivel médio para computadorxcomputador

### ISSUE THREAD

**Issue by flavioduart** [flavioduart/informatica29VelhandoeCeiando#31]
Ideias de como criar ou adaptar a função de nível médio para a função computadorxcomputador?

**Comment by caahreginaa** [comment]
Ja temos uma funcao de jogada a nivel medio, agora e so criarmor outra funcao computador x computador ou usar condicoes na ja existente para quando o usuario escolher medio ou dificil.

**Comment by caahreginaa** [comment]
Editei o código para que fosse perguntado ao usuário o nível da partida computador x computador, agora o nível é enviado para a função e dependendo do nível escolhido, a jogada sera de nível fácil ou médio. :dancer:
