### ISSUE TITLE
Erro na escolha do jogador

### ISSUE THREAD

**Issue by flavioduart** [flavioduart/informatica29VelhandoeCeiando#33]
Percebi agora que quando inicia a opção de jogo humano x computador ele pede para digitarmos 'c' ou 'h' para as opções de quem irá começar, mas caso aperte qualquer outra letra ele não apresenta mensagem de erro. Como podemos resolver isso?

**Comment by caahreginaa** [comment]
Testei agora e vi que ele nao apresenta mensagem de erro e segue adiante. Podemos usar um do while para repetir a pergunta ate que o usuario digite algo valido. A mensagem de erro fica a criterio de voces, mas nao acho necessario, ja que vai estar na tela o que deveria ter sido digitado.

**Comment by caahreginaa** [comment]
Ja que o erro ja foi corrigido, fecharei aqui :dancer:
