### ISSUE TITLE
implementação da função possoganhar

### ISSUE THREAD

**Issue by eilins** [flavioduart/informatica29VelhandoeCeiando#34]
Supondo que as jogadas para ganhar o jogo estejam empatadas entre computador e humano, e ao invés do computador fazer a jogada para impedir do humano ganhar, ele jogar para ganhar, o que vocês acham melhor nesse caso? Implementar uma nova função para caso ocorra essa condição ocorra ou só adicionar nos ifs da jogada de nível médio a condição? Lembrando que apenas implementar estaria a mercê da sorte do OU na condição ser referente a linha/coluna/diagonal para ele completar o próprio jogo. O que vocês me dizem?

**Comment by caahreginaa** [comment]
Acho melhor implementar uma nova funcao, ate para que a funcao de jogada a nivel medio nao fique tao grande.

**Comment by flavioduart** [comment]
Vinicius, não tive tempo de comentar antes, mas acho uma boa ideia implementar uma nova função, o código fica mais detalhado!!

**Comment by eilins** [comment]
Ok, função implementada. Deem uma olhada depois.
