### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by caahreginaa** [flavioduart/informatica29VelhandoeCeiando#35]
Amados, acho que deveríamos adicionar alguns comentários para que o nosso código fique mais fácil de ser lido.

**Comment by flavioduart** [comment]
Concordo, amada, sempre é bom deixar ele mais fácil de entender.

**Comment by eilins** [comment]
Concordo também. :)

**Comment by eilins** [comment]
Comentários descritivos adicionados!
