### ISSUE TITLE
Organização do código

### ISSUE THREAD

**Issue by caahreginaa** [flavioduart/informatica29VelhandoeCeiando#36]
Pessoal, acredito que seria aconselhável que colocássemos os protótipos das funções em uma determinada ordem lógica e que essas funções aparecessem nessa ordem no código, para que fique mais organizado.

**Comment by flavioduart** [comment]
Boa ideia Cássia, também tava pensando sobre isso. Eu apoio.

**Comment by eilins** [comment]
Por mim, beleza. Manda brasa.

**Comment by eilins** [comment]
Organização do código listadas na ordem dos protótipos feita!
