### ISSUE TITLE
Padronização de variáveis

### ISSUE THREAD

**Issue by caahreginaa** [flavioduart/informatica29VelhandoeCeiando#38]
Pessoal, acredito que seria valido se padronizássemos as variáveis. Por exemplo: em quase todas as funções utilizamos uma variável que armazena de quem é a vez de jogar, então essa variável poderia ter sempre o nome de vez.

**Comment by flavioduart** [comment]
Cássia, como sempre com ótimas ideias! :nail_care:

**Comment by eilins** [comment]
Cassia, sim é uma boa! Como sempre, lacrando :)

**Comment by caahreginaa** [comment]
Variáveis foram padronizadas.
