### ISSUE TITLE
rand

### ISSUE THREAD

**Issue by eilins** [flavioduart/informatica29VelhandoeCeiando#40]
Galera, como fazer um rand com apenas 3 números?

**Comment by flavioduart** [comment]
Vinícius, como o nosso MAX é até 3, então você pode usar ele. X= rand()%MAX.
Mas se você quiser um rand com qualquer outro número, você declara uma variável com um valor e substitui no MAX, por exemplo: 

int r=4;

X= rand()%r.

entendeu?

**Comment by eilins** [comment]
Entendi!  Valeeeeeus :dancers:
