### ISSUE TITLE
switch na função nivel dificil

### ISSUE THREAD

**Issue by eilins** [flavioduart/informatica29VelhandoeCeiando#43]
Na função nível difícil, para cada condição que criarmos, teremos de fazer um switch com cases para as posições das casas escolhidas pelo usuário?

**Comment by flavioduart** [comment]
Sim, pois como é o nível mais difícil, é bom sempre, para toda condição, as casas serem aleatórias de acordo com a estratégia que implantamos. Assim o jogador nunca poderá decorar as jogadas, pois serão sempre aleatórias. :dancer:

**Comment by eilins** [comment]
Ok, massa.
