### ISSUE TITLE
Programa pronto 

### ISSUE THREAD

**Issue by flavioduart** [flavioduart/informatica29VelhandoeCeiando#50]
Galera, nosso código está pronto, conseguimos! Agora vamos dar clone do repositório na pasta de trabalhos do servidor, e estará tudo feito! :confetti_ball: :heart_eyes:

**Comment by caahreginaa** [comment]
Clone dado! :+1: :clap:

**Comment by eilins** [comment]
Clone dado! :nail_care: :fireworks:
