### ISSUE TITLE
Esqueleto

### ISSUE THREAD

**Issue by caahreginaa** [flavioduart/informatica29VelhandoeCeiando#6]
Sugiro adicionarmos hoje a noite pelo menos um esqueleto do programa já com os protótipos de alguns funções, bibliotecas, códigos do caracteres especiais para formar a tabela e afins.

**Comment by flavioduart** [comment]
Vou adicionar o esqueleto agora.

**Comment by caahreginaa** [comment]
:+1:

**Comment by wesleysilas** [comment]
eu tambem vou adicionar...

**Comment by flavioduart** [comment]
Esqueleto adicionado :tada:
