### ISSUE TITLE
Adaptação para tabela UTF-8

### ISSUE THREAD

**Issue by eilins** [flavioduart/informatica29VelhandoeCeiando#8]
Pessoal, há um problema na formatação da coluna direita da tabela, toda ela fica construída integralmente, mas o seu lado direito fica com alguns espaçamentos. Vou disponibilizar o código, para vocês verem se acham o que ta ocasionando isso.

**Comment by caahreginaa** [comment]
Tentarei corrigir o problema

**Comment by flavioduart** [comment]
Creio que ajeitando apenas os printf que são responsáveis pelo lado direito dará resultado.

**Comment by caahreginaa** [comment]
Fiz algumas alterações das posições dos printfs na função e mudei tbm as variáveis. Problema resolvido
