### ISSUE TITLE
Melhoria da tabela

### ISSUE THREAD

**Issue by flavioduart** [flavioduart/informatica29VelhandoeCeiando#9]
Pessoal, olhando a tabela pronta, achei que ficaria mais "a cara" do jogo da velha" sem ter as bordas verticais; queria saber a opinião de vocês.

**Comment by caahreginaa** [comment]
As bordas da parte externa no caso? Eu concordo, acho que ficaria bem mais característico de jogo da velha

**Comment by eilins** [comment]
Por mim, pode ser também!

**Comment by flavioduart** [comment]
Já que todos estão de acordo, tudo bem. :v:

**Comment by flavioduart** [comment]
Mudança feita!
